### ISSUE TITLE
Weird random value

### ISSUE THREAD

**Issue by samth** [plum-umd/try-scv-racket#10]
This program:

```
(module f racket
  (provide/contract [f ((lambda (x) #t) . -> . integer?)])
  (define (f n)
    (/ 1 (- 100 n))))
```

Randomly fails on this value, apparently: `(struct● 0.634)`

**Comment by philnguyen** [comment]
Ugliness revealed :D

`struct•` was what I "invented" to denote a privately declared struct.

In an untyped language, we can have this situation:

``` racket
(define (f x)
  (cond
   [(number? x) …]
   [(string? x) …]
   …
   [(known-structᵢ? x) …]
   …
   [else …]))
```

If the `else` branch assumes some operation on its argument, a privately declared struct (from another module) flowing to that branch can cause an error. I use `struct•` as a way to denote privately declared data from some other module, but maybe there's a way to make the message more intuitive.

When generating counterexamples, if the opaque value subsumes numbers, I just generate a random number for it. If the opaque value's refinement prevents numbers, I resort to `struct•`. In this case, it's the error where `-` is performed on a non-number. Maybe I should try using this sparingly to avoid confusion. In this case, I could try harder by checking if it a string or a boolean will do.

**Comment by philnguyen** [comment]
This happens when the opaque value has the form `• / (not/c number?) (not/c string?) …`, so we can try as hard as we want for a concrete value that the refinement doesn't exclude. An unknown struct from an other module is something we can always resort to.

**Comment by samth** [comment]
Why does it contain 0.634 then?

If this is just an arbitrary value that isn't a known kind of thing, then (a) the counterexample program is wrong and (b) the printing could be better.

For a working counterexample, this will do: `(let () (define-struct s ()) (s))`
