### ISSUE TITLE
Bogus counterexample

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/try-scv-racket#12]
Here's a small modification to the div100 example:

```
(module f racket
  (provide/contract
    [f (integer? . -> . integer?)])

  (define (f n)
    (if (= n 100)
        5
        (/ 1 (- 100 n)))))
```

The verifier comes back with:

```
Contract violation: 'f' violates its own contract. Value 1.0 violates predicate integer? An example module that breaks it: (module user racket (require (submod ".." f)) (f 99))
```

There are several weird things to note: it thinks the result is 1.0 and not 1; it also considers 1.0 as not an `integer?`.  Moreover, this counterexample is bogus (it is in fact the only integer argument that is safe!)

It is not a counterexample as demonstrated by adding and running:

```
(require 'f)
(f 99)
```

which produces 1, as expected.

**Comment by philnguyen** [comment]
This was because I never encoded the contract `(not/c integer?)`. The Z3 query looked something like this:

``` lisp
(declare-const X Int)
(declare-const L0 Int)
(declare-const L1 Real)
(assert (not (= L1 0)))
(assert (= L1 (/ 1 (to_real L0))))
(assert (= L0 (- 100 X)))
(assert (not (= X 100)))
(check-sat)
(get-model)
```

which gives back:

``` lisp
sat
(model 
  (define-fun X () Int
    99)
  (define-fun L1 () Real
    1.0)
  (define-fun L0 () Int
    1))
```

On the heap, `L1` is also constrained by `(not/c integer?)`, so I added another assertion:

``` lisp
(assert (not (is_int L1)))
```

Unfortunately, Z3 doesn't solve this kind of query well:

``` lisp
unknown
Z3(10, 10): ERROR: model is not available
```

so the verifier now reports a _possible_ violation, but generates no counterexample:

```
Possible contract violation: 'f' violates its own contract.
Value contrained by contracts
 (not/c integer?)
 real?
 (≠/c 0)
 (=/c (/ 1 …₁))
violates predicate
 integer?
```

**Comment by dvanhorn** [comment]
I'm not sure I follow... but a real number can be an integer.  1.0 is an
integer, for example.

David

**Comment by philnguyen** [comment]
Originally `L1` was a `real?`, then tested against contract `integer?`, which ambiguously passed and failed. When translating the fail branch to Z3, I didn't translate the `(not/c integer?)` refinement, so Z3 gave `1.0` as an instantiation. Plugging this back to the heap, I got the weird error saying `1.0` violating `integer?`.
