### ISSUE TITLE
Two repos

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/try-scv-racket#13]
There are two repos at work in the SCV web repl: try-scv-racket and soft-contract.  I've been submitting reports to try-scv-racket since that's what I'm using to discover bugs, but it is often the case that the fix comes from changing soft-contract.

What should we do about this?  I don't want to maintain two sets of tests (but I hope changes to soft-contract come with their own tests).

Should we merge the web repl and soft-contract repositories so there is only code base?

**Comment by samth** [comment]
I think having a separate repo for the web page is useful. What we need is just a way to tell which place things should go.

**Comment by dvanhorn** [comment]
@philnguyen : can you make soft-contract provide a (local) REPL that does the same thing as the web REPL?  That way I can locally check bugs and file them with soft-contract when I can reproduce it or file it with try-scv-racket whenever I can't?

**Comment by philnguyen** [comment]
You can install `soft-contract` (the [racket](https://github.com/philnguyen/soft-contract/tree/racket) branch) locally and run `#lang soft-contract`. There are some [examples](https://github.com/philnguyen/soft-contract/tree/racket/examples). Is this what you want?

**Comment by philnguyen** [comment]
Or if you don't want to have to set up Z3, you can use the one on the server too, as long as `/srv/www/racket/bin/racket` and `/srv/www/z3/bin/z3` are in `PATH`.

**Comment by dvanhorn** [comment]
OK, so I think you should move these tests to soft-contract.  I will start filing bug reports there when they are independent of the web REPL.
