### ISSUE TITLE
Security vulnerability in web repl

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/try-scv-racket#15]
This program shuts the web server down when run:

```
(system "kill `ps -A | grep 'main.rkt' | awk '{print $1}'`")
```

I'm sure worse things could be executed as well.

This seems like a sandbox configuration issue that needs to be fixed.  In the meantime I've shut down the server until its resolved.

Look at try-racket for guidance since it doesn't suffer the same problem:

```
Make some Racket!
> (require racket/system)
> (system "kill `ps -A | grep 'main.rkt' | awk '{print $1}'`")
subprocess: `execute' access denied for /bin/sh
context...:
/usr/share/racket/collects/racket/system.rkt:174:0: do-system*/exit-code
/usr/share/racket/collects/racket/system.rkt:213:0: system46
/usr/share/racket/pkgs/sandbox-lib/racket/sandbox.rkt:379:0: call-with-limits
/usr/share/racket/pkgs/sandbox-lib/racket/sandbox.rkt:475:0: call-with-custodian-shutdown
/usr/share/racket/collects/racket/private/more-scheme.rkt:147:2: call-with-break-parameterization
/usr/share/racket/pkgs/sandbox-lib/racket/sandbox.rkt:837:5: loop
>  
```

**Comment by philnguyen** [comment]
This problem resulted from me copying and pasting. I added `execute` permission to the `scv` evaluator to allow it to run Z3, then carried that over to the `racket` evaluator. I just removed all unneccessary permission from the `racket` evaluator, making it identical to the original `try-racket` one now.

`scv` doesn't have side effects, so it's safe to allow it to execute `/bin/sh` for now, but I think there's a better way to get more fine grained control over this.

**Comment by dvanhorn** [comment]
On 1/8/15, 3:03 AM, Phil Nguyen wrote:

> This problem resulted from me copying and pasting. I added |execute|
> permission to the |scv| evaluator to allow it to run Z3, then carried
> that over to the |racket| evaluator. I just removed all unneccessary
> permission from the |racket| evaluator, making it identical to the
> original |try-racket| one now.
> 
> |scv| doesn't have side effects, so it's safe to allow it to execute
> |/bin/sh| for now, but I think there's a better way to get more fine
> grained control over this.

OK, server restarted.
