### ISSUE TITLE
No error message for no contract definition

### ISSUE THREAD

**Issue by cmentzer** [plum-umd/try-scv-racket#29]
Below is a functioning module that the verifier correctly marks as safe: 

```
(module foo racket
  (provide (contract-out [div2 ((and/c integer? (>/c 0)) . -> . real?)]))
  (define (div2 n)
    (/ n 2)))
```

if we remove the contract definition for the function div2: 

```
(module foo racket
  (define (div2 n)
    (/ n 2)))
```

the verifier still marks the program as safe. But if we attempt to run the function:

```
(module foo racket
  (define (div2 n)
    (/ n 2)))

(require 'foo) 
(div2 5)
```

we get the following error:

```
div2: undefined;
 cannot reference an identifier before its definition
  in module: 'program
```

Should the verifier recognize when a function has no contract defined and throw an error? Also: is it possible to change the runtime error from "div2 undefined" to "div2 needs a contract" or something more accurate like that?

**Comment by philnguyen** [comment]
Our system allows a module to have private definitions. In this case, `foo` does not export `div2`, so nobody can ever cause it to be blamed.
