### ISSUE TITLE
Program safe, but not

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/try-scv-racket#3]
Verifying `(+ 1 "asd")` gives "Program is safe" but it isn't.

**Comment by philnguyen** [comment]
It's because the verifier ignores blames on the top-level. I realized this could be confusing to the user, so I only documented a program as a sequence of modules.

**Comment by philnguyen** [comment]
Wait i think at some point I hacked it by turning a top-level expression to another sub-module. Something is wrong. I'll check this.
